baseurl = "https://claytonrichey.com"
languageCode = "en-us"
title = "Clayton Richey's blog"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
# disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command
# themesDir = "../.."

[params]
    site_author = "Clayton Richey"
    site_description = "The blog of Clayton Richey."
    location = "USA"
    # Link custom assets relative to /static
    #avatar = "img/profile-image.png"
    avatar = "img/profile.png"
    header_background = "img/desk.jpg"
    # header_title = "Customizable header title"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    linkedin  = "clayton-richey-65216b22"
    github    = "Odoth"
    bitbucket = "Odoth"
    gplus     = ""
